#!/usr/bin/env node
// Reads ~/.insurwreck/credentials.json (written by /insurwreck:start) and
// writes .env.local, so nobody copies a key by hand. Run via `npm run setup`.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const credsPath = join(homedir(), ".insurwreck", "credentials.json");

if (!existsSync(credsPath)) {
  console.error(
    `\nCouldn't find credentials at ${credsPath}\n\n` +
      "Ask Claude to run /insurwreck:start first — that registers you for the " +
      "hackathon and writes this file. Then re-run: npm run setup\n"
  );
  process.exit(1);
}

let creds;
try {
  creds = JSON.parse(readFileSync(credsPath, "utf8"));
} catch {
  console.error(`\n${credsPath} exists but isn't valid JSON. Ask Claude to run /insurwreck:start again.\n`);
  process.exit(1);
}

const anthropic = creds.services?.anthropic;
const resend = creds.services?.resend;
const supabase = creds.services?.supabase;
const participant = creds.participant;

if (!anthropic?.api_key || !anthropic?.api_base) {
  console.error(
    "\nCredentials file is missing services.anthropic.api_key / api_base. " +
      "Ask Claude to run /insurwreck:status to check what's issued, or " +
      "/insurwreck:start to re-provision.\n"
  );
  process.exit(1);
}

if (!resend?.api_key || !resend?.from) {
  console.error(
    "\nCredentials file is missing services.resend.api_key / from. " +
      "Ask Claude to run /insurwreck:status to check what's issued, or " +
      "/insurwreck:start to re-provision.\n"
  );
  process.exit(1);
}

const lines = [
  "# generated by `npm run setup` — do not commit",
  "",
  `ANTHROPIC_API_KEY=${anthropic.api_key}`,
  `ANTHROPIC_BASE_URL=${anthropic.api_base}`,
  "",
  `RESEND_API_KEY=${resend.api_key}`,
  `RESEND_FROM="${resend.from}"`,
  "",
];

if (supabase?.url && supabase?.service_role_key) {
  lines.push(
    "# optional — only used if you flip the switch in lib/claims.ts",
    `SUPABASE_URL=${supabase.url}`,
    `SUPABASE_SERVICE_ROLE_KEY=${supabase.service_role_key}`,
    ""
  );
} else {
  lines.push("# optional — no Supabase project on file, seed data only", "SUPABASE_URL=", "SUPABASE_SERVICE_ROLE_KEY=", "");
}

if (participant?.name) lines.push(`NEXT_PUBLIC_PARTICIPANT_NAME="${participant.name}"`);
if (participant?.idea_brief) lines.push(`NEXT_PUBLIC_IDEA_BRIEF="${participant.idea_brief}"`);

writeFileSync(join(process.cwd(), ".env.local"), lines.join("\n") + "\n");

console.log("\nWrote .env.local from your Insurwreck credentials. Run: npm run dev\n");
